$file = 'e:\Client_Workspace\project_CAF\client\src\components\AdminPage.tsx'
$lines = [System.IO.File]::ReadAllLines($file)

$newSection = @(
'',
'                                          <div className="grid gap-3">',
'                                             {(() => {',
'                                                const requirements = new Map<string, { label: string, required: boolean, instruction?: string }>();',
'                                                selectedApp.selectedServices.forEach(s => {',
'                                                   s.requiredDocuments?.forEach(rd => {',
'                                                      if (!requirements.has(rd.label) || (!requirements.get(rd.label)!.required && rd.required)) {',
'                                                         requirements.set(rd.label, rd);',
'                                                      }',
'                                                   });',
'                                                });',
'                                                ',
'                                                const reqList = Array.from(requirements.values());',
'                                                const attachments = selectedApp.attachments || [];',
'                                                const requests = selectedApp.requestedFiles || [];',
'',
'                                                return (',
'                                                  <>',
'                                                    {reqList.map((req, i) => {',
'                                                      const attachment = attachments.find(a => a.label === req.label);',
'                                                      const request = requests.find(rf => rf.name === req.label && rf.status === ''Pending'');',
'',
'                                                      if (attachment) {',
'                                                        return (',
'                                                          <div key={`req-slot-${i}`} className="flex items-center justify-between p-4 bg-white border border-black/5 rounded-sm hover:shadow-sm transition-all group">',
'                                                            <div className="flex items-center gap-4">',
'                                                              <div className="w-10 h-10 bg-black/5 rounded-sm flex items-center justify-center text-black/20 group-hover:bg-green-50 group-hover:text-green-500 transition-colors">',
'                                                                <FileText size={18} />',
'                                                              </div>',
'                                                              <div className="flex flex-col">',
'                                                                <span className="text-xs font-bold text-black/80">{req.label}</span>',
'                                                                <span className="text-[8px] uppercase tracking-widest font-bold text-black/30">',
'                                                                  {attachment.uploadedBy} • {new Date(attachment.uploadedAt).toLocaleDateString()}',
'                                                                </span>',
'                                                              </div>',
'                                                            </div>',
'                                                            <div className="flex items-center gap-2">',
'                                                              <button ',
'                                                                onClick={() => handleViewAttachment(attachment)}',
'                                                                className="p-2 hover:bg-black/5 rounded-sm transition-colors text-black/40 hover:text-black"',
'                                                              >',
'                                                                <Eye size={14} />',
'                                                              </button>',
'                                                              <button className="p-2 hover:bg-black/5 rounded-sm transition-colors text-black/40 hover:text-black">',
'                                                                <Download size={14} />',
'                                                              </button>',
'                                                            </div>',
'                                                          </div>',
'                                                        );',
'                                                      }',
'',
'                                                      return (',
'                                                        <div key={`req-slot-${i}`} className={`flex items-center justify-between p-4 border rounded-sm group ${request ? ''bg-indigo-50/30 border-indigo-100'' : ''bg-black/[0.01] border-black/5 border-dashed''}`}>',
'                                                          <div className="flex items-center gap-4">',
'                                                            <div className={`w-10 h-10 rounded-sm flex items-center justify-center ${request ? ''bg-indigo-500 text-white animate-pulse'' : ''bg-black/5 text-black/20''}`}>',
'                                                              <Clock size={18} />',
'                                                            </div>',
'                                                            <div className="flex flex-col">',
'                                                              <span className={`text-xs font-bold ${request ? ''text-indigo-900'' : ''text-black/40''}`}>',
'                                                                {request ? `Awaiting: ${req.label}` : `Missing: ${req.label}`}',
'                                                              </span>',
'                                                              <span className="text-[8px] uppercase tracking-widest font-bold text-black/20">',
'                                                                {req.required ? ''Mandatory Requirement'' : ''Optional Requirement''}',
'                                                              </span>',
'                                                            </div>',
'                                                          </div>',
'                                                          {!request && (',
'                                                            <button ',
'                                                              onClick={() => {',
'                                                                setRequestFileName(req.label);',
'                                                                setRequestFileNote(req.instruction || "");',
'                                                                setIsRequestModalOpen(true);',
'                                                              }}',
'                                                              className="px-3 py-1 bg-black/[0.02] hover:bg-black text-black/40 hover:text-white rounded-sm text-[8px] font-bold uppercase tracking-widest transition-all"',
'                                                            >',
'                                                              Request',
'                                                            </button>',
'                                                          )}',
'                                                          {request && (',
'                                                            <div className="text-[8px] font-black uppercase tracking-tighter text-indigo-300">',
'                                                              Req. {new Date(request.requestedAt).toLocaleDateString()}',
'                                                            </div>',
'                                                          )}',
'                                                        </div>',
'                                                      );',
'                                                    })}',
'',
'                                                    {/* Other/Legacy Attachments */}',
'                                                    {attachments.filter(a => !reqList.some(r => r.label === a.label)).map((doc, i) => (',
'                                                      <div key={`extra-doc-${i}`} className="flex items-center justify-between p-4 bg-white border border-black/5 rounded-sm hover:shadow-sm transition-all group">',
'                                                         <div className="flex items-center gap-4">',
'                                                            <div className="w-10 h-10 bg-black/5 rounded-sm flex items-center justify-center text-black/20 group-hover:bg-indigo-50 group-hover:text-indigo-500 transition-colors">',
'                                                               <FileText size={18} />',
'                                                            </div>',
'                                                            <div className="flex flex-col">',
'                                                               <span className="text-xs font-bold text-black/80">{doc.label || doc.name}</span>',
'                                                               <span className="text-[8px] uppercase tracking-widest font-bold text-black/30">',
'                                                                  {doc.uploadedBy} • {new Date(doc.uploadedAt).toLocaleDateString()}',
'                                                               </span>',
'                                                            </div>',
'                                                         </div>',
'                                                         <div className="flex items-center gap-2">',
'                                                            <button ',
'                                                               onClick={() => handleViewAttachment(doc)}',
'                                                               className="p-2 hover:bg-black/5 rounded-sm transition-colors text-black/40 hover:text-black"',
'                                                            >',
'                                                               <Eye size={14} />',
'                                                            </button>',
'                                                            <button className="p-2 hover:bg-black/5 rounded-sm transition-colors text-black/40 hover:text-black">',
'                                                               <Download size={14} />',
'                                                            </button>',
'                                                         </div>',
'                                                      </div>',
'                                                    ))}',
'',
'                                                    {/* Extra Pending Requests */}',
'                                                    {requests.filter(rf => rf.status === ''Pending'' && !reqList.some(r => r.label === rf.name)).map((rf, i) => (',
'                                                      <div key={`extra-req-${i}`} className="flex items-center justify-between p-4 bg-indigo-50/50 border border-indigo-100 rounded-sm group">',
'                                                        <div className="flex items-center gap-4">',
'                                                          <div className="w-10 h-10 bg-indigo-500 text-white rounded-sm flex items-center justify-center animate-pulse">',
'                                                            <Clock size={18} />',
'                                                          </div>',
'                                                          <div className="flex flex-col">',
'                                                            <span className="text-xs font-bold text-indigo-900">Awaiting: {rf.name}</span>',
'                                                            <span className="text-[8px] uppercase tracking-widest font-bold text-indigo-400">',
'                                                              Requested on {new Date(rf.requestedAt).toLocaleDateString()}',
'                                                            </span>',
'                                                          </div>',
'                                                        </div>',
'                                                        <div className="text-[8px] font-black uppercase tracking-tighter text-indigo-300">',
'                                                          Custom Request',
'                                                        </div>',
'                                                      </div>',
'                                                    ))}',
'                                                  </>',
'                                                );',
'                                             })()}',
'                                          </div>'
)

# Lines are 0-indexed in the array, so line 791 is index 790
# We want to replace lines 792-850 (indices 791-849)
$startIdx = 791  # line 792 (0-indexed)
$endIdx = 849    # line 850 (0-indexed)

$before = $lines[0..($startIdx - 1)]
$after = $lines[($endIdx + 1)..($lines.Length - 1)]

$newLines = $before + $newSection + $after

[System.IO.File]::WriteAllLines($file, $newLines, [System.Text.UTF8Encoding]::new($false))
Write-Host "Done! New line count: $($newLines.Length)"
